# Reference : https://docs.travis-ci.com/user/languages/android/
language: android

# Only trusty distributions are supported for Android.
dist: trusty

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools

    # The BuildTools version used by your project
    - build-tools-29.0.2

    # The SDK version used to compile your project
    - android-29

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

  licenses:
    # Accept all Android licenses.
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

stages:
  - name: build
  - name: deploy
    if: branch = master AND repo = heig-PRO-b04/android-frontend


jobs:
  include:
    - stage: build
      script:
        - echo 'apiUrl="https://api.rockin.app"' > local.properties
        - ./gradlew clean assembleProductionAPI testProductionAPIDebugUnitTest
    - stage: deploy
      script:
        - echo 'This is where deployment goes'
